version: '3.8'

services:
  postman-app:
    container_name: postman-app
    build:
      context: .
      dockerfile: postman.Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./migartions:/app/migrations
      - ./main.py:/app/main.py
    depends_on:
      - db
      - redis
    ports:
      - 5000:5000
    restart: on-failure

  db:
    container_name: postman-app-postgress
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker

  pgadmin:
    container_name: postman-app-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    user: ${UID}:${GID}
    depends_on:
      - db
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80

  redis:
    container_name: postman-app-redis
    image: redis:6.2
    ports:
      - 6379:6379

  redis-ui:
    container_name: postman-app-redis-ui
    image: marian/rebrow
    ports:
      - 5001:5001
    depends_on:
      - redis
